export let preguntas = [
    {idQuest:1,
    pregunta:"¿Qué es un bucle for en programación?",
    opc1:"Una estructura de control que se ejecuta un número específico de veces.",
    opc2:"Una función para imprimir mensajes en pantalla.",
    opc3:"Un tipo de dato en JavaScript.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res1",
    id2:"res2",
    id3:"res3",
    id4:"res4"},
    {idQuest:2,
    pregunta:"¿Cuál es la diferencia entre una lista y una tupla en Python?",
    opc1:"Las listas son inmutables, mientras que las tuplas son mutables.",
    opc2:"Las listas están ordenadas, mientras que las tuplas no lo están.",
    opc3:"Las listas se definen con corchetes [], mientras que las tuplas se definen con paréntesis ().",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res5",
    id2:"res6",
    id3:"res7",
    id4:"res8"},
    {idQuest:3,
    pregunta:"¿Qué hace el operador '==' en la mayoría de los lenguajes de programación?",
    opc1:"Asigna un valor a una variable.",
    opc2:"Compara dos valores para ver si son iguales.",
    opc3:"Multiplica dos números.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res9",
    id2:"res10",
    id3:"res11",
    id4:"res12"},
    {idQuest:4,
    pregunta:"¿Qué es un constructor en Java?",
    opc1:"Una función que construye una instancia de una clase.",
    opc2:"Una variable estática en una clase.",
    opc3:"Una clase que hereda de otra clase.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res13",
    id2:"res14",
    id3:"res15",
    id4:"res16"},
    {idQuest:5,
    pregunta:"¿Cuál de las siguientes afirmaciones describe mejor la recursividad en programación?",
    opc1:"Es una estructura de datos en forma de árbol.",
    opc2:"Es un enfoque donde una función se llama a sí misma para resolver un problema más pequeño.",
    opc3:"Es una forma de iteración que utiliza bucles.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res17",
    id2:"res18",
    id3:"res19",
    id4:"res20"},
    {idQuest:6,
    pregunta:"¿Qué es HTML?",
    opc1:"Un lenguaje de programación de alto nivel.",
    opc2:"Un protocolo de transferencia de hipertexto.",
    opc3:"Un lenguaje de marcado para crear páginas web.",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res21",
    id2:"res22",
    id3:"res23",
    id4:"res24"},
    {idQuest:7,
    pregunta:"¿Qué significa CSS y para qué se utiliza comúnmente?",
    opc1:"Cascading Style Sheets, se utiliza para agregar interactividad a las páginas web.",
    opc2:"Colorful Style Sheets, se utiliza para crear esquemas de color en las páginas web.",
    opc3:"Cascading Style Sheets, se utiliza para aplicar estilos visuales a las páginas web.",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res25",
    id2:"res26",
    id3:"res27",
    id4:"res28"},
    {idQuest:8,
    pregunta:"¿Cuál es el propósito principal de un índice en una base de datos?",
    opc1:"Ordenar los datos de la base de datos alfabéticamente.",
    opc2:"Acelerar la búsqueda y recuperación de datos.",
    opc3:"Definir las relaciones entre tablas.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res29",
    id2:"res30",
    id3:"res31",
    id4:"res32"},
    {idQuest:9,
    pregunta:"¿Qué es un algoritmo de ordenamiento?",
    opc1:"Un conjunto de reglas para organizar datos de una manera particular.",
    opc2:"Una función en JavaScript para crear nuevas matrices.",
    opc3:"Un método para definir relaciones en una base de datos.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res33",
    id2:"res34",
    id3:"res35",
    id4:"res36"},
    {idQuest:10,
    pregunta:"¿Qué hace la función `print()` en Python?",
    opc1:"Muestra un mensaje en la consola.",
    opc2:"Calcula la suma de dos números.",
    opc3:"Define una variable.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res37",
    id2:"res38",
    id3:"res39",
    id4:"res40"},
    {idQuest:11,
    pregunta:"¿Qué es un operador lógico 'AND'?",
    opc1:"Devuelve verdadero si uno de los operandos es verdadero.",
    opc2:"Devuelve verdadero si ambos operandos son verdaderos.",
    opc3:"Devuelve verdadero si ninguno de los operandos es verdadero.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res41",
    id2:"res42",
    id3:"res43",
    id4:"res44"},
    {idQuest:12,
    pregunta:"¿Qué significa JSON y dónde se utiliza comúnmente?",
    opc1:"JavaScript Object Notation, se utiliza para representar datos estructurados.",
    opc2:"Java Object Network, se utiliza para comunicación entre objetos Java.",
    opc3:"JavaScript Ordered Numbers, se utiliza para ordenar números en JavaScript.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res45",
    id2:"res46",
    id3:"res47",
    id4:"res48"},
    {idQuest:13,
    pregunta:"¿Qué es un bucle while en programación?",
    opc1:"Una estructura de control que se ejecuta un número específico de veces.",
    opc2:"Una estructura de control que se repite hasta que una condición se convierte en falsa.",
    opc3:"Una función que imprime mensajes en pantalla.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res49",
    id2:"res50",
    id3:"res51",
    id4:"res52"},
    {idQuest:14,
    pregunta:"¿Qué es una variable en programación?",
    opc1:"Un valor constante que no cambia.",
    opc2:"Una función que devuelve un resultado.",
    opc3:"Un contenedor para almacenar datos que pueden cambiar durante la ejecución del programa.",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res53",
    id2:"res54",
    id3:"res55",
    id4:"res56"},
    {idQuest:15,
    pregunta:"¿Qué es un IDE y para qué se utiliza?",
    opc1:"Un lenguaje de programación popular utilizado para desarrollo web.",
    opc2:"Un entorno de desarrollo integrado, se utiliza para escribir, compilar y depurar código.",
    opc3:"Una función en JavaScript para crear efectos visuales.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res57",
    id2:"res58",
    id3:"res59",
    id4:"res60"},
    {idQuest:16,
    pregunta:"¿Qué es una función en programación?",
    opc1:"Una estructura de control que repite un bloque de código.",
    opc2:"Un contenedor para almacenar datos.",
    opc3:"Un conjunto de instrucciones que realiza una tarea específica y puede ser reutilizado.",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res61",
    id2:"res62",
    id3:"res63",
    id4:"res64"},
    {idQuest:17,
    pregunta:"¿Qué es un parámetro en una función?",
    opc1:"Una variable que almacena un valor constante.",
    opc2:"Una variable que almacena datos que pueden cambiar durante la ejecución del programa.",
    opc3:"Un valor que se pasa a una función cuando se llama.",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res65",
    id2:"res66",
    id3:"res67",
    id4:"res68"},
    {idQuest:18,
    pregunta:"¿Qué es el control de versiones en el desarrollo de software?",
    opc1:"Un proceso para verificar la validez del código.",
    opc2:"Un sistema para administrar cambios en el código fuente.",
    opc3:"Una técnica para mejorar el rendimiento del código.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res69",
    id2:"res70",
    id3:"res71",
    id4:"res72"},
    {idQuest:19,
    pregunta:"¿Qué es un repositorio en Git?",
    opc1:"Un lugar donde se almacenan archivos y carpetas.",
    opc2:"Una función en JavaScript para trabajar con arreglos.",
    opc3:"Un lugar donde se almacena el historial de cambios de un proyecto de software.",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res73",
    id2:"res74",
    id3:"res75",
    id4:"res76"},
    {idQuest:20,
    pregunta:"¿Qué es la programación orientada a objetos?",
    opc1:"Un enfoque para escribir programas que se basa en la interacción entre objetos.",
    opc2:"Un enfoque para escribir programas que se basa en funciones.",
    opc3:"Un enfoque para escribir programas que se basa en bucles.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res77",
    id2:"res78",
    id3:"res79",
    id4:"res80"},
    {idQuest:21,
    pregunta:"¿Cuál es la diferencia entre un método y una función en programación orientada a objetos?",
    opc1:"No hay diferencia, ambos términos son sinónimos.",
    opc2:"Un método se define dentro de una clase, mientras que una función no.",
    opc3:"Un método se define fuera de una clase, mientras que una función se define dentro de una clase.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res81",
    id2:"res82",
    id3:"res83",
    id4:"res84"},
    {idQuest:22,
    pregunta:"¿Qué es una excepción en programación?",
    opc1:"Un error que ocurre durante la ejecución de un programa.",
    opc2:"Una función que maneja errores en un programa.",
    opc3:"Un tipo de dato en Python.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res85",
    id2:"res86",
    id3:"res87",
    id4:"res88"},
    {idQuest:23,
    pregunta:"¿Qué es la herencia en programación orientada a objetos?",
    opc1:"Un concepto que permite a una clase heredar propiedades y métodos de otra clase.",
    opc2:"Un concepto que permite a una clase contener instancias de otras clases.",
    opc3:"Un concepto que permite a una clase acceder a propiedades y métodos de otra clase.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res89",
    id2:"res90",
    id3:"res91",
    id4:"res92"},
    {idQuest:24,
    pregunta:"¿Qué es un puntero en lenguajes de programación como C o C++?",
    opc1:"Una variable que almacena la dirección de memoria de otra variable.",
    opc2:"Una función que devuelve un valor.",
    opc3:"Una estructura de datos en forma de árbol.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res93",
    id2:"res94",
    id3:"res95",
    id4:"res96"},
    {idQuest:25,
    pregunta:"¿Qué es un paradigma de programación?",
    opc1:"Un conjunto de reglas para escribir código de forma clara y legible.",
    opc2:"Un estilo o enfoque para resolver problemas mediante la programación.",
    opc3:"Una función en JavaScript para crear objetos.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res97",
    id2:"res98",
    id3:"res99",
    id4:"res100"},
    {idQuest:26,
    pregunta:"¿Qué es un ciclo de vida de software?",
    opc1:"Un proceso para desarrollar software que incluye planificación, diseño, desarrollo, pruebas y mantenimiento.",
    opc2:"Un proceso para administrar cambios en el código fuente.",
    opc3:"Una técnica para mejorar el rendimiento del código.",
    opc4:"Ninguna de las anteriores.",
    res:"1",
    id1:"res101",
    id2:"res102",
    id3:"res103",
    id4:"res104"},
    {idQuest:27,
    pregunta:"¿Qué es un bug en el desarrollo de software?",
    opc1:"Una característica deseada del software.",
    opc2:"Un error o defecto en el código que produce un comportamiento no deseado.",
    opc3:"Una función en JavaScript para realizar operaciones matemáticas.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res105",
    id2:"res106",
    id3:"res107",
    id4:"res108"},
    {idQuest:28,
    pregunta:"¿Qué es un ciclo de desarrollo ágil?",
    opc1:"Un enfoque para el desarrollo de software que se basa en planificación a largo plazo.",
    opc2:"Un enfoque para el desarrollo de software que se basa en iteraciones cortas y colaboración.",
    opc3:"Una técnica para mejorar el rendimiento del código.",
    opc4:"Ninguna de las anteriores.",
    res:"2",
    id1:"res109",
    id2:"res110",
    id3:"res111",
    id4:"res112"},
    {idQuest:29,
    pregunta:"¿Qué es un patrón de diseño en el desarrollo de software?",
    opc1:"Una técnica para mejorar el rendimiento del código.",
    opc2:"Un conjunto de reglas para escribir código de forma clara y legible.",
    opc3:"Una solución general a un problema común en el desarrollo de software.",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res113",
    id2:"res114",
    id3:"res115",
    id4:"res116"},
    {idQuest:30,
    pregunta:"¿Qué es un API en el desarrollo de software?",
    opc1:"Una función en JavaScript para crear objetos.",
    opc2:"Un conjunto de reglas para escribir código de forma clara y legible.",
    opc3:"Una interfaz que permite a diferentes sistemas de software comunicarse entre sí.",
    opc4:"Ninguna de las anteriores.",
    res:"3",
    id1:"res117",
    id2:"res118",
    id3:"res119",
    id4:"res120"}
    
];
